export type Clue = {
  type: string
  text: string
  image?: string // local asset path for an image clue (radiograph, karyotype, …)
  detail?: string // expandable explanation from the sheet's drop-down column
  reference?: string // raw citation (DOI or URL) extracted from the detail
}

// Maps a diagnosis → { clue number → image asset path }. Generated by the
// sync-images script from the sheet's in-cell images and merged in at parse time.
export type CaseImageManifest = Record<string, Record<string, string>>

export type TCase = {
  id: number
  diagnosis: string
  aliases: string[]
  category: string
  clues: Clue[]
  description?: string
  management?: string
}

export type Guess = { text: string; correct: boolean }

export type Status = 'playing' | 'won' | 'lost'

export type DailyProgress = {
  caseId: number
  guesses: Guess[]
  status: Status
}

export type Stats = {
  played: number
  wins: number
  streak: number
  best: number | null
  lastPlayedDate: string | null
  distribution: number[] // index 0 → solved in 1 guess, …, index 5 → solved in 6
}
