export type Clue = {
  type: string
  text: string
  image?: string // local asset path for an image clue (radiograph, karyotype, …)
  detail?: string // expandable explanation from the sheet's drop-down column
  reference?: string // raw citation (DOI or URL) extracted from the detail
}

// Maps a diagnosis → { clue number → image asset path }. Generated by the
// sync-images script from the sheet's in-cell images and merged in at parse time.
export type CaseImageManifest = Record<string, Record<string, string>>

export type TCase = {
  id: number
  diagnosis: string
  aliases: string[]
  category: string // the "Week"/block label
  unlockDate: string | null // YYYY-MM-DD; case enters the pool on/after this date. null = always available.
  clues: Clue[]
  description?: string
  management?: string
}

export type Year = '1' | '2'

// The baked bank: one case pool per year. Generated by scripts/sync-data.ts.
export type CasesByYear = Record<Year, TCase[]>

// `passed` marks a skipped turn: the player had no guess, spent an attempt to
// reveal the next clue. Always `correct: false`; the flag lets the UI and share
// grid distinguish a deliberate skip from a wrong diagnosis.
export type Guess = { text: string; correct: boolean; passed?: boolean }

export type Status = 'playing' | 'won' | 'lost'

export type DailyProgress = {
  caseId: number
  guesses: Guess[]
  status: Status
}

export type Stats = {
  played: number
  wins: number
  streak: number // current daily win streak
  maxStreak: number // longest daily win streak ever
  best: number | null // fewest guesses in a win (kept for history; not surfaced)
  lastPlayedDate: string | null
  distribution: number[] // index 0 → solved in 1 guess, …, index 5 → solved in 6
}
